-- 19. ABC reporting: Compute the revenue generated by each customer based on their orders. Also, show each customer's revenue as a percentage of total revenue. Sort by customer name.
SELECT 
	c.customerName, 
	SUM(od.priceEach * od.quantityOrdered) AS customer_revenue, 
    ROUND((SUM(od.priceEach * od.quantityOrdered) / (SELECT SUM(od.priceEach * od.quantityOrdered)
		FROM orders o
        JOIN orderdetails od ON od.orderNumber = o.orderNumber)) * 100, 2) AS revenue_percentage
FROM orderdetails od
JOIN orders o ON od.orderNumber = o.orderNumber
JOIN customers c ON o.customerNumber = c.customerNumber
GROUP BY c.customerName
ORDER BY c.customerName;