-- 24. Compute the profit generated by each product line, sorted by profit descending.
SELECT
	p.productLine,
	ROUND(SUM((od.priceEach - p.buyPRice) * od.quantityOrdered), 2) AS productline_profit
FROM orderdetails od
JOIN orders o ON od.orderNumber = o.orderNumber
JOIN products p ON od.productCode = p.productCode
GROUP BY p.productLine
ORDER BY productline_profit DESC;