-- 20. Compute the profit generated by each customer based on their orders. Also, show each customer's profit as a percentage of total profit. Sort by profit descending.
SELECT
c.customerName,
ROUND(SUM((od.priceEach - p.buyPrice) * od.quantityOrdered), 2) AS customer_profit,
ROUND((SUM((od.priceEach - p.buyPrice) * od.quantityOrdered) /
	(SELECT SUM((od.priceEach - p.buyPrice) * od.quantityOrdered) 
	FROM orderdetails od
	JOIN products p ON od.productCode = p.productCode)) * 100, 2) AS profit_percentage
FROM orderdetails od
JOIN orders o ON od.orderNumber = o.orderNumber
JOIN products p ON od.productCode = p.productCode
JOIN customers c ON o.customerNumber = c.customerNumber
GROUP BY c.customerName
ORDER BY customer_profit DESC;