-- 21. Compute the revenue generated by each sales representative based on the orders from the customers they serve.
SELECT 
	c.salesRepEmployeeNumber, 
	ROUND(SUM(od.priceEach * od.quantityOrdered), 2) AS salesrep_revenue
FROM orderdetails od
JOIN orders o ON od.orderNumber = o.orderNumber
JOIN customers c ON o.customerNumber = c.customerNumber
WHERE c.salesRepEmployeeNumber IS NOT NULL
GROUP BY c.salesRepEmployeeNumber
ORDER BY salesrep_revenue DESC;