-- 23. Compute the revenue generated by each product, sorted by product name.
SELECT
	p.productName,
	ROUND(SUM(od.priceEach * od.quantityOrdered), 2) AS product_revenue
FROM orderdetails od
JOIN orders o ON od.orderNumber = o.orderNumber
JOIN products p ON od.productCode = p.productCode
GROUP BY p.productName
ORDER BY p.productName;