-- 22. Compute the profit generated by each sales representative based on the orders from the customers they serve. Sort by profit generated descending.
SELECT
	c.salesRepEmployeeNumber,
	ROUND(SUM((od.priceEach - p.buyPrice) * od.quantityOrdered), 2) AS salesrep_profit
FROM orderdetails od
JOIN orders o ON od.orderNumber = o.orderNumber
JOIN products p ON od.productCode = p.productCode
JOIN customers c ON o.customerNumber = c.customerNumber
WHERE c.salesRepEmployeeNumber IS NOT NULL
GROUP BY c.salesRepEmployeeNumber
ORDER BY salesrep_profit DESC;